[2024-05-05T13:41:35.794+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T13:41:36.044+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_complex.get_entry_result manual__2024-05-05T13:41:12.244644+00:00 [queued]>
[2024-05-05T13:41:36.143+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_complex.get_entry_result manual__2024-05-05T13:41:12.244644+00:00 [queued]>
[2024-05-05T13:41:36.147+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-05T13:41:36.294+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): get_entry_result> on 2024-05-05 13:41:12.244644+00:00
[2024-05-05T13:41:36.364+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_complex', 'get_entry_result', 'manual__2024-05-05T13:41:12.244644+00:00', '--job-id', '19', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_complex.py', '--cfg-path', '/tmp/tmp_lc9nem4']
[2024-05-05T13:41:36.373+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask get_entry_result
[2024-05-05T13:41:36.419+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1295) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T13:41:36.427+0000] {standard_task_runner.py:63} INFO - Started process 1424 to run task
[2024-05-05T13:41:36.613+0000] {task_command.py:426} INFO - Running <TaskInstance: example_complex.get_entry_result manual__2024-05-05T13:41:12.244644+00:00 [running]> on host b274a178a74a
[2024-05-05T13:41:37.104+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_complex' AIRFLOW_CTX_TASK_ID='get_entry_result' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T13:41:12.244644+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T13:41:12.244644+00:00'
[2024-05-05T13:41:37.120+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T13:41:37.124+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-05T13:41:37.126+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo get_entry_result']
[2024-05-05T13:41:37.204+0000] {subprocess.py:86} INFO - Output:
[2024-05-05T13:41:37.218+0000] {subprocess.py:93} INFO - get_entry_result
[2024-05-05T13:41:37.224+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-05T13:41:37.224+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T13:41:37.314+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=example_complex, task_id=get_entry_result, execution_date=20240505T134112, start_date=20240505T134136, end_date=20240505T134137
[2024-05-05T13:41:37.499+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-05T13:41:37.526+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T13:41:37.539+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
